-- MySQL Script generated by MySQL Workbench
-- dom 25 may 2014 03:45:31 CDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alertasocial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alertasocial` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `alertasocial` ;

-- -----------------------------------------------------
-- Table `alertasocial`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertasocial`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NOT NULL,
  `firstname` VARCHAR(99) NULL,
  `lastname` VARCHAR(99) NULL,
  `email` VARCHAR(99) NULL,
  `description` TEXT NULL,
  `twitter_access_token` VARCHAR(45) NOT NULL,
  `twitter_access_secret` VARCHAR(45) NOT NULL,
  `twitter_user_id` VARCHAR(45) NOT NULL,
  `new_user` ENUM('0','1') NOT NULL DEFAULT '1',
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` ENUM('subscriber', 'ong') NOT NULL DEFAULT 'subscriber',
  `validated` ENUM('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `alertasocial`.`alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertasocial`.`alert` (
  `alert_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(99) NOT NULL,
  `content` TEXT NOT NULL,
  `status` ENUM('new','published','archived') NOT NULL DEFAULT 'new',
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `action_link` VARCHAR(255) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alert_id`),
  UNIQUE INDEX `campaign_id_UNIQUE` (`alert_id` ASC),
  INDEX `fk_alert_user_idx` (`user_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `alertasocial`.`user_has_subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertasocial`.`user_has_subscribers` (
  `user_has_subscribers_id` INT UNSIGNED NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `subscriber_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_has_subscribers_id`),
  INDEX `fk_user_has_subscriber_user1_idx` (`user_id` ASC),
  INDEX `fk_user_has_subscriber_user2_idx` (`subscriber_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `alertasocial`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertasocial`.`category` (
  `category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `alertasocial`.`user_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertasocial`.`user_has_categories` (
  `user_has_categories_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_has_categories_id`),
  INDEX `fk_user_has_categories_user1_idx` (`user_id` ASC),
  INDEX `fk_user_has_categories_category1_idx` (`category_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `alertasocial`.`alert_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alertasocial`.`alert_has_categories` (
  `alert_has_categories_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `alert_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alert_has_categories_id`),
  INDEX `fk_alert_has_categories_alert1_idx` (`alert_id` ASC),
  INDEX `fk_alert_has_categories_category1_idx` (`category_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
